# Generated by Django 6.1 on 2026-08-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.tutor')),
            ],
        ),
    ]
