# Generated by Django 6.1 on 2026-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0002_alter_booking_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='historical-booking@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
